#!/bin/sh
mkdir -p "$HOME/.cache/snooze"
exec snooze -w 1 -s 7d -t "$HOME/.cache/snooze/weekly" -- sh -c \
  "test -d $HOME/.config/cron.weekly && run-parts --lsbsysinit $HOME/.config/cron.weekly; : > $HOME/.cache/snooze/weekly"
