#!/usr/bin/env bash

# Most of the ideas are stolen from: https://github.com/SwayKh/dotfiles/blob/main/river/init
# So if you like the way this works, consider dropping a *star* on the original author ^
# Links to default init and wiki if you get lost
# https://codeberg.org/river/river/src/branch/master/example/init
# https://codeberg.org/river/wiki

#-----------------------------------------------------#
#                      SETTINGS                       #
#-----------------------------------------------------#

browser="firefox"
mail="thunderbird"
term="footclient" # <- If you want single instance change: "footclient" > "foot"
fterm="$term -a float-term"
tfm="foot -e yazi"
drun="j4-dmenu-desktop --dmenu='bemenu_runner -B1 -n -l10 -p drun:'"
run="bemenu_runner run --no-exec -B1 -n -p run: -l10 | xargs riverctl spawn"
emoji="$HOME/.local/bin/bemenu_emoji"
powermenu="$HOME/.local/bin/bemenu_power"
screenshot="$HOME/.local/bin/wl-shot"
recmenu="$HOME/.local/bin/bemenu_screenshot"
calendar="foot -W 125x30 -a float-call -e calcure"
clip="bemenu_clipboard"

# Waybar signals
sig_1="pkill -RTMIN+1 waybar"
sig_2="pkill -RTMIN+2 waybar"
sig_3="pkill -RTMIN+3 waybar"
#sig_4="pkill -RTMIN+4 waybar"

# Inputs
mouse="pointer-9610-54-Glorious_Model_O" # <- Find your inputs by typing "riverctl list-inputs"
riverctl set-repeat 30 300
riverctl keyboard-layout -options caps:escape "fi" # <- caps as escape + lang
riverctl focus-follows-cursor normal
riverctl input "$mouse" accel-profile flat
riverctl input "$mouse" pointer-accel 0

#-----------------------------------------------------#
#                      Look                           #
#-----------------------------------------------------#

riverctl background-color 0x000000
riverctl border-color-focused 0x525252
riverctl border-color-urgent 0xa2191f
riverctl border-color-unfocused 0x262626
riverctl border-width 1

#-----------------------------------------------------#
#                      lauout                         #
#-----------------------------------------------------#

riverctl default-attach-mode bottom
riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 0 &

#-----------------------------------------------------#
#                      LAUNCH                         #
#-----------------------------------------------------#

riverctl map normal Super D spawn "$drun"
riverctl map normal Super+Shift D spawn "$run"
riverctl map normal Super R spawn "$tfm"
riverctl map normal Super+Shift p spawn "$powermenu"
riverctl map normal Super Return spawn "$term"
riverctl map normal Super F1 spawn "noti_sysnfo"
riverctl map normal Super F2 spawn "noti_usage cpu"
riverctl map normal Super F7 spawn "$calendar"
riverctl map normal Super F10 spawn "foot -a float-u -e popupgrade"
riverctl map normal Super+Shift F2 spawn "noti_usage ram"
riverctl map normal Super+Control E spawn "$emoji"
riverctl map normal Super F4 spawn "bemenu_killer"
riverctl map normal Super+Control Print spawn "$recmenu"
riverctl map normal Super F9 spawn "$HOME/.config/river/scripts/mic-toggle.sh && $sig_2"
riverctl map normal Super F11 spawn "$HOME/.config/river/scripts/locker.sh"
riverctl map normal Super+Shift F11 spawn "$HOME/.config/river/scripts/swayidle-toggle.sh && $sig_1"
riverctl map normal Super W spawn "$browser"
riverctl map normal Super Y spawn "$tfm"
riverctl map normal Super M spawn "$mail"
riverctl map normal Super Print spawn "$screenshot -f"
riverctl map normal Super+Shift Print spawn "$screenshot -re"
riverctl map normal Super+Control P spawn "colorpicker_fancy"
riverctl map normal Super+Control W spawn "noti_weather"
riverctl map normal Super+Control T spawn "noti_date"
riverctl map normal Super N spawn "foot -e nvim ~/Documents/personal/notes/index.md"
riverctl map normal Super+Shift N spawn "$term -e ~/.local/bin/quick_note"
riverctl map normal Super T spawn "$fterm -W 100x30 -e nvim ~/Documents/personal/notes/todo.md"
riverctl map normal Super+Shift Delete spawn "$fterm -W 120x35 -e htop"
riverctl map normal Super+Shift C spawn "$clip"
riverctl map normal Super+Control spawn- "$calendar"
riverctl map normal Super F12 spawn "$HOME/.config/river/scripts/dot-settings.sh"
riverctl map normal Super B spawn "$HOME/.config/river/scripts/waybar-toggle.sh"

#-----------------------------------------------------#
#                      BINDS                          #
#-----------------------------------------------------#

# Close the focused view
riverctl map -repeat normal Super Q close
# Reload config
riverctl map normal Super+Control R spawn "$HOME/.config/river/init && notify-send -a center_notify 'River' 'Config reloaded'"
# Focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super Down focus-view next
riverctl map normal Super Up focus-view previous
# Swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super+Shift Down swap next
riverctl map normal Super+Shift Up swap previous
# Focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
# Send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous
# Bump the focused view to the top of the layout stack
riverctl map normal Super BackSpace zoom
riverctl map normal Super z zoom
# Decrease/increase the main ratio of rivertile(1)
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super Right send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super Left send-layout-cmd rivertile "main-ratio -0.05"
# Increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift Prior send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift Next send-layout-cmd rivertile "main-count -1"
# Move views
riverctl map -repeat normal Super+Control Left move left 25
riverctl map -repeat normal Super+Control Down move down 25
riverctl map -repeat normal Super+Control Up move up 25
riverctl map -repeat normal Super+Control Right move right 25
# Resize views
riverctl map -repeat normal Super+Alt Left resize horizontal -25
riverctl map -repeat normal Super+Alt Down resize vertical 25
riverctl map -repeat normal Super+Alt Up resize vertical -25
riverctl map -repeat normal Super+Alt Right resize horizontal 25
# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view
# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view
# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float
# Super+Space to toggle float
riverctl map normal Super Space toggle-float
# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen
# Use cursed arrow keys: Super+Alt{F10,F12,F11,F9} to change layout orientation
riverctl map normal Super+Alt J send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Alt K send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt H send-layout-cmd rivertile "main-location left"
riverctl map normal Super+Alt L send-layout-cmd rivertile "main-location right"
# Media keys
riverctl map -repeat normal None XF86AudioRaiseVolume spawn "$HOME/.config/river/scripts/volume.sh up && $sig_3"
riverctl map -repeat normal None XF86AudioLowerVolume spawn "$HOME/.config/river/scripts/volume.sh down && $sig_3"
riverctl map normal None XF86AudioMute spawn "$HOME/.config/river/scripts/volume.sh mute && $sig_3"
riverctl map normal None XF86AudioPlay spawn "$HOME/.config/river/scripts/mediactrl.sh --play"
riverctl map normal None XF86AudioPrev spawn "$HOME/.config/river/scripts/mediactrl.sh --prv"
riverctl map normal None XF86AudioNext spawn "$HOME/.config/river/scripts/mediactrl.sh --nxt"
riverctl map normal None XF86AudioStop spawn "$HOME/.config/river/scripts/mediactrl.sh --stop"
riverctl map normal Super+Control M spawn "$HOME/.config/river/scripts/mediactrl.sh --noti"
riverctl map normal None XF86Calculator spawn "galculator"

#-----------------------------------------------------#
#                      TAGS                           #
#-----------------------------------------------------#

# Focus between tags
for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super $i set-focused-tags $tags

  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal Super+Shift $i set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control $i toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
# Super+0 to focus all tags / Super+Shift+0 to tag focused view with all tags
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Scratchpad tags
scratchpad="$HOME/.config/river/scripts/scratchpads.sh"
editor_tag=$((1 << 11))
secrets_tag=$((1 << 12))
chat_tag=$((1 << 13))
tfm_tag=$((1 << 15))
dyn_tag=$((1 << 14))

scratch_tags=$((terminal_tag | editor_tag | secrets_tag | dyn_tag | chat_tag))
all_but_scratch_tag=$((all_tags ^ scratch_tags))
riverctl spawn-tagmask ${all_but_scratch_tag}

# Spawn hidden workspaces
riverctl map normal Super+Shift E spawn "$scratchpad nvim"
riverctl map normal Super F5 spawn "$scratchpad keepassxc"
riverctl map normal Super F6 spawn "$scratchpad discord"
riverctl map normal Super+Shift R spawn "$scratchpad yazi"
# Toggle the scratchpad(s)
riverctl map normal Super C toggle-focused-tags "${chat_tag}"
riverctl map normal Super R toggle-focused-tags "${tfm_tag}"
# Sway-like dynamic warkspace(tag)
riverctl map normal Super+Shift Minus set-view-tags "${dyn_tag}"
riverctl map normal Super Minus toggle-focused-tags "${dyn_tag}"

# Sticky tag
sticky_tag=$((1 << 31))
all_tags=$(((1 << 32) - 1))
all_but_sticky_tag=$(($all_tags ^ $sticky_tag))

riverctl map normal Super+Shift Y toggle-view-tags $sticky_tag
riverctl spawn-tagmask ${all_but_sticky_tag}

# Modify the normal keybind to always select the sticky tag
for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))
  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super $i set-focused-tags $(($sticky_tag + $tags))
done

#-----------------------------------------------------#
#                      RULES                          #
#-----------------------------------------------------#

# Spawn to
riverctl rule-add -app-id "Thunderbird" tags $((1 << (3 - 1)))
riverctl rule-add -app-id "Signal" tags $((1 << (3 - 1)))
riverctl rule-add -app-id "Firefox" tags $((1 << (2 - 1)))
riverctl rule-add -app-id "steam" tags $((1 << (5 - 1)))
riverctl rule-add -app-id "com.discordapp.Discord" tags $chat_tag
riverctl rule-add -app-id "vesktop" tags $chat_tag
riverctl rule-add -app-id "virt-manager" tags $((1 << (8 - 1)))
riverctl rule-add -app-id "com.transmissionbt.transmission_*" tags $((1 << (4 - 1)))
riverctl rule-add -app-id "org.keepassxc.KeePassXC" tags $secrets_tag
# Floaters
riverctl rule-add -app-id "Choose User Profile" float
riverctl rule-add -app-id "Firefox" -title "About Mozilla Firefox" float
riverctl rule-add -app-id "Firefox" -title "Library" float
riverctl rule-add -app-id "Firefox" -title "Picture-in-Picture" float
riverctl rule-add -app-id "GParted" float
riverctl rule-add -app-id "KeePassXC" -title "Browser Access Request" float
riverctl rule-add -app-id "KeePassXC" -title "Passkey credentials" float
riverctl rule-add -app-id "vesktop" float
riverctl rule-add -app-id "blueman-manager" float
riverctl rule-add -app-id "float-*" float
riverctl rule-add -app-id "Gimp" float
riverctl rule-add -app-id "floatterm" float
riverctl rule-add -app-id "galculator" float
riverctl rule-add -app-id "imv" float
riverctl rule-add -app-id "mpv" float
riverctl rule-add -app-id "nm-connection-editor" float
riverctl rule-add -app-id "nwg-look" float
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" float
riverctl rule-add -app-id "quick_note" float
riverctl rule-add -app-id "steam" float
riverctl rule-add -app-id "thunar" -title "Confirm to replace files" float
riverctl rule-add -app-id "thunar" -title "File Operation Progress" float
riverctl rule-add -app-id "xdg-desktop-portal-gtk" float
riverctl rule-add -title "Picture-in-Picture" float
riverctl rule-add -title "gtk*" float
riverctl rule-add -title "popup title with spaces" float
riverctl rule-add -title "zoom" float
# Decorations
riverctl rule-add ssd
riverctl rule-add -app-id "steam" csd

#-----------------------------------------------------#
#                      START                           #
#-----------------------------------------------------#

bash "$HOME/.config/river/autostart.sh"
