font=JetBrains Mono:pixelsize=14, Symbols Nerd Font Mono:pixelsize=14
pad=5x5 center

# fixes transparent padding in sway: https://codeberg.org/dnkl/foot/issues/1675
 resize-by-cells=no

[main]
include=~/.config/foot/themes/oxocarbon-v2.ini
