[icons]
icons = "material-nf"

[theme]
theme = "native"

# Weather
#[[block]]
#block = "weather"
#autolocate = true
#interval = 3600
#format = " $location $temp "
#format_alt = " (forecast) {$temp_favg ({$temp_fmin}-{$temp_fmax})|Unavailable} "
#[block.service]
#name = "metno"
#forecast_hours = 6

# Swayidle toggle
[[block]]
block = "custom"
command = "$HOME/.config/i3status-rust/scripts/swayidle.sh"
hide_when_empty = true
interval = "once"
signal = 1
[[block.click]]
button = "left"
cmd = "~/.config/river/scripts/swayidle-toggle.sh; pkill -RTMIN+1 i3status-rs"

# Pipewire
[[block]]
block = "custom"
command = "$HOME/.config/i3status-rust/scripts/pipewire.sh"
interval = "once"
signal = 3
[[block.click]]
button = "left"
cmd = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle; pkill -RTMIN+3 i3status-rs"
[[block.click]]
button = "right"
cmd = "pavucontrol"

# Mic toggle
[[block]]
block = "custom"
command = "$HOME/.config/i3status-rust/scripts/mic.sh"
interval = "once"
hide_when_empty = true
signal = 2
[[block.click]]
button = "left"
cmd = "wpctl set-mute @DEFAULT_SOURCE@ toggle; pkill -RTMIN+2 i3status-rs"

#[[block]]
#block = "custom"
#command = "$HOME/.config/i3status-rust/scripts/discord.sh"
#interval = 10
#hide_when_empty = true
#[[block.click]]
#button = "left"
#cmd = "$HOME/.config/river/scripts/scratchpads.sh discord"

# Battery
[[block]]
block = "battery"
format = " $icon "
missing_format = ""

# Network
[[block]]
block = "net"
interval = 5
format = " $icon "
missing_format = "x"
inactive_format = "Network disconnected"
[[block.click]]
button = "right"
cmd = "networkmanager_dmenu"

# Clock
[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%d.%m %H:%M') "
[[block.click]]
button = "left"
cmd = "noti_cal"
[[block.click]]
button = "right"
cmd = "noti_weather"
[block.theme_overrides]
#idle_bg = "#262626"

# Power
[[block]]
block = "custom"
interval = "once"
format = "󰐥  "
command = ""
[[block.click]]
button = "left"
cmd = "bemenu_power"
